/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RemoteInterfaceImpl */

#ifndef _Included_RemoteInterfaceImpl
#define _Included_RemoteInterfaceImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef RemoteInterfaceImpl_serialVersionUID
#define RemoteInterfaceImpl_serialVersionUID -3215090123894869218LL
#undef RemoteInterfaceImpl_serialVersionUID
#define RemoteInterfaceImpl_serialVersionUID -4100238210092549637LL
#undef RemoteInterfaceImpl_serialVersionUID
#define RemoteInterfaceImpl_serialVersionUID 4974527148936298033LL
#undef RemoteInterfaceImpl_serialVersionUID
#define RemoteInterfaceImpl_serialVersionUID 1LL
/*
 * Class:     RemoteInterfaceImpl
 * Method:    CppLocalTime
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_RemoteInterfaceImpl_CppLocalTime
  (JNIEnv *, jobject, jstring);

/*
 * Class:     RemoteInterfaceImpl
 * Method:    CppLocalOS
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_RemoteInterfaceImpl_CppLocalOS
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
